### ISSUE TITLE
clutter-gst

### ISSUE THREAD

**Issue by acornejo** [djdeath/clutter-android#2]
I want to write a gstreamer source for clutter and add it to the clutter-gst project.

I am wondering where is the right place to have a discussion on what is the best approach to do this. Unfortunately I can't find a website with contact information for clutter-gst, so I am posting this issue here since I notice you are a big contributor to clutter-gst.

Cheers.

**Comment by djdeath** [comment]
You can file a bug on the Gnome bugzilla : https://bugzilla.gnome.org/enter_bug.cgi?product=clutter-gst
Or alternatively ask questions on the clutter mailing list : https://mail.gnome.org/mailman/listinfo/clutter-list

**Comment by acornejo** [comment]
Thanks! I opened a bug report on bugzilla https://bugzilla.gnome.org/show_bug.cgi?id=741277, hopefully I'll get some feedback there, otherwise I'll try the email list.
